spring.application.name=demo5

spring.config.import=optional:.env[.properties]
spring.datasource.url=${DB.URL}
spring.datasource.username=${DB.ID}
spring.datasource.password=${DB.PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true